import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import QueryProvider from "@/components/query-provider";
import { Toaster } from "sonner";
import Link from "next/link";
import { ModeToggle } from "@/components/ui/mode-toggle";
import MonitoringMount from "@/components/monitoring-mount";
import SessionProvider from "@/components/session-provider";
import OfflineBanner from "@/components/offline-banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <ThemeProvider>
          <QueryProvider>
            <SessionProvider>
            <header className="border-b">
              <div className="mx-auto max-w-7xl px-4 py-3 flex items-center justify-between">
                <Link href="/" className="font-semibold">CuraNet</Link>
                <div className="flex items-center gap-3">
                  <SyncStatus />
                  <ModeToggle />
                </div>
              </div>
            </header>
            <OfflineBanner />
            <main className="mx-auto max-w-7xl px-4 py-6">{children}</main>
            <Toaster richColors position="top-right" />
            <MonitoringMount />
            </SessionProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

function SyncStatus() {
  // TODO: wire to offline/sync engine
  return (
    <span className="inline-flex items-center gap-2 text-sm text-muted-foreground">
      <span className="size-2 rounded-full bg-emerald-500" aria-hidden />
      Synced
    </span>
  );
}
